language: cpp
sudo: required
git:
    submodules: false
matrix: 
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      python: 3.6
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: 
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      python: 3.6

before_install:
  - git submodule update --init --depth=1
  - sudo apt install make cmake pkg-config
  - sudo apt install libassimp-dev libglfw3-dev libglew-dev
  - sudo apt install libeigen3-dev
  - mkdir -p ~/.mujoco
  - wget https://www.roboti.us/download/mujoco200_linux.zip
  - unzip mujoco200_linux.zip -d ~/.mujoco/
  - eval "${MATRIX_EVAL}"
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n travis_env python=3.6 setuptools numpy scipy
  - conda activate travis_env
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$HOME/miniconda/envs/travis_env/bin/python3.6 -DPYTHON_LIBRARY=$HOME/miniconda/envs/travis_env/lib/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$HOME/miniconda/envs/travis_env/include/python3.6m ..
  - make -j4