language: cpp
sudo: required
git:
    submodules: false
matrix: 
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      python: 3.6
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: 
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      python: 3.6

before_install:
  - git submodule update --init --depth=1
  - sudo apt install make cmake pkg-config
  - sudo apt install libassimp-dev libglfw3-dev libglew-dev
  - sudo apt install libeigen3-dev
  - mkdir -p ~/.mujoco
  - wget https://www.roboti.us/download/mujoco200_linux.zip
  - unzip mujoco200_linux.zip -d ~/.mujoco/
  - eval "${MATRIX_EVAL}"
  - |
    if [ -n "$PYTHON" ]; then
      pip install --user --upgrade pip virtualenv
      virtualenv -p $(which python3) venv
      source venv/bin/activate
    fi
  - python --version
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.6 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.6m ..
  - make -j4